export const FETCH_IMAGE_REQUEST = 'FETCH_IMAGE_REQUEST';
export const FETCH_IMAGE_SUCCESS = 'FETCH_IMAGE_SUCCESS';
export const FETCH_IMAGE_FAILURE = 'FETCH_IMAGE_FAILURE';
export const FETCH_IMAGE_PENDING = 'FETCH_IMAGE_PENDING';

export const SET_CURRENT_IMAGE = 'SET_CURRENT_IMAGE';

